#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Jun 01 00:40:49 ACST 2026
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
maxShadowRenderDistance=10
shaderPack=ComplementaryReimaginedModifiedByNathanLithia
enableShaders=true
